apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-backend-v1
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-backend-v1
  template:
    metadata:
      labels:
        app: myapp-backend-v1
    spec:
      containers:
        - name: myapp-backend
          image: esatcbr/myapp-backend:v1-slim
          ports:
            - containerPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-backend-v2
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-backend-v2
  template:
    metadata:
      labels:
        app: myapp-backend-v2
    spec:
      containers:
        - name: myapp-backend
          image: esatcbr/myapp-backend:v2
          ports:
            - containerPort: 5000
