apiVersion: v1
kind: Service
metadata:
  name: myapp-backend-v1
  namespace: myapp
spec:
  selector:
    app: myapp-backend-v1
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-backend-v2
  namespace: myapp
spec:
  selector:
    app: myapp-backend-v2
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

