apiVersion: v1
kind: Pod
metadata:
  name: ambassador-pod
  labels:
    app: ambassador-pod
spec:
  containers:
  - name: myapp
    image: esatcbr/myapp-backend:v1-slim
    ports:
    - containerPort: 5000
  - name: nginx-ambassador
    image: esatcbr/ambassadors-nginx:v1
    ports:
    - containerPort: 80

