apiVersion: v1
kind: Service
metadata:
  name: ambassador-service
spec:
  type: LoadBalancer  # Dışarıdan erişim için LoadBalancer tipi
  selector:
    app: ambassador-pod  # Pod'un etiketi
  ports:
    - port: 80           # Dışarıya açılacak port
      targetPort: 80     # nginx-ambassador container'ındaki port
